import 'package:hive_ce_flutter/hive_flutter.dart';
import 'package:zamaan/core/constants/hive_type_ids.dart';
import 'package:zamaan/core/extensions/string.dart';

part 'reference_type.g.dart';

/// Enum representing different reference types.
/// This enum is used for categorizing references (e.g., a task vs. a sub-task)
/// in the VM. It is strictly for VM purposes and is not meant for database storage.
@HiveType(typeId: EnumHiveTypeIds.referenceType)
enum ReferenceType {
  @HiveField(0)
  task,
  @HiveField(1)
  subTask;

  /// Retrieves the [ReferenceType] corresponding to the provided [name].
  /// Comparison is case-insensitive and uses the display name generated by [toSentenceCase].
  ///
  /// Example:
  /// ```dart
  /// final ref = ReferenceType.fromName("Task");
  /// print(ref); // Output: ReferenceType.task
  /// ```
  static ReferenceType fromName(String name) => ReferenceType.values.firstWhere(
        (e) => e.name.toLowerCase() == name.toLowerCase(),
        orElse: () => throw Exception('Invalid ReferenceType name: $name'),
      );

  /// Returns a user-friendly string representation of the reference type.
  /// It takes the enum value (e.g. "task" or "subTask"), splits the string, and
  /// applies [toSentenceCase] to format it properly for VM display.
  ///
  /// Example:
  /// ```dart
  /// print(ReferenceType.subTask.name); // Output: "Sub task"
  /// ```
  String get name => toString().split('.').last.toSentenceCase();
}
