// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:zamaan/features/sync/domain/enums/os.dart';
import 'package:zamaan/features/task_center/data/models/local/category_hive_model.dart';
import 'package:zamaan/features/task_center/data/models/local/custom_measurement_unit_hive_model.dart';
import 'package:zamaan/features/task_center/data/models/local/goal_hive_model.dart';
import 'package:zamaan/features/task_center/data/models/local/schedule/date_range_hive_model.dart';
import 'package:zamaan/features/task_center/data/models/local/schedule/schedule_constraints_hive_model.dart';
import 'package:zamaan/features/task_center/data/models/local/schedule/scheduled_day_time_hive_model.dart';
import 'package:zamaan/features/task_center/data/models/local/schedule/scheduled_interval_hive_model.dart';
import 'package:zamaan/features/task_center/data/models/local/schedule/scheduled_occurrence_hive_model.dart';
import 'package:zamaan/features/task_center/data/models/local/schedule/time_range_hive_model.dart';
import 'package:zamaan/features/task_center/data/models/local/tag_hive_model.dart';
import 'package:zamaan/features/task_center/data/models/local/task/sub_task_hive_model.dart';
import 'package:zamaan/features/task_center/data/models/local/task/task_hive_model.dart';
import 'package:zamaan/shared/data/models/local/user/user_hive_model.dart';
import 'package:zamaan/shared/domain/enums/hive/day_type.dart';
import 'package:zamaan/shared/domain/enums/hive/goal_constraint.dart';
import 'package:zamaan/shared/domain/enums/hive/interval_unit.dart';
import 'package:zamaan/shared/domain/enums/hive/measurement_category.dart';
import 'package:zamaan/shared/domain/enums/hive/measurement_unit.dart';
import 'package:zamaan/shared/domain/enums/hive/occurrence_status.dart';
import 'package:zamaan/shared/domain/enums/hive/os.dart';
import 'package:zamaan/shared/domain/enums/hive/priority.dart';
import 'package:zamaan/shared/domain/enums/hive/reference_type.dart';
import 'package:zamaan/shared/domain/enums/hive/registration_status.dart';
import 'package:zamaan/shared/domain/enums/hive/repetition_type.dart';
import 'package:zamaan/shared/domain/enums/hive/schedule_type.dart';
import 'package:zamaan/shared/domain/enums/hive/scheduled_time_mode.dart';
import 'package:zamaan/shared/domain/enums/hive/sync_action.dart';
import 'package:zamaan/shared/domain/enums/hive/task_status.dart';
import 'package:zamaan/shared/domain/enums/hive/week_day.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryHiveModelAdapter());
    registerAdapter(CustomMeasurementUnitHiveModelAdapter());
    registerAdapter(DateRangeHiveModelAdapter());
    registerAdapter(DayTypeAdapter());
    registerAdapter(GoalConstraintAdapter());
    registerAdapter(GoalHiveModelAdapter());
    registerAdapter(IntervalUnitAdapter());
    registerAdapter(MeasurementCategoryAdapter());
    registerAdapter(MeasurementUnitAdapter());
    registerAdapter(OSAdapter());
    registerAdapter(OSAdapter());
    registerAdapter(OccurrenceStatusAdapter());
    registerAdapter(PriorityAdapter());
    registerAdapter(ReferenceTypeAdapter());
    registerAdapter(RegistrationStatusAdapter());
    registerAdapter(RepetitionTypeAdapter());
    registerAdapter(ScheduleConstraintsHiveModelAdapter());
    registerAdapter(ScheduleTypeAdapter());
    registerAdapter(ScheduledDayTimeHiveModelAdapter());
    registerAdapter(ScheduledIntervalHiveModelAdapter());
    registerAdapter(ScheduledOccurrenceHiveModelAdapter());
    registerAdapter(ScheduledTimeModeAdapter());
    registerAdapter(SubTaskHiveModelAdapter());
    registerAdapter(SyncActionAdapter());
    registerAdapter(TagHiveModelAdapter());
    registerAdapter(TaskHiveModelAdapter());
    registerAdapter(TaskStatusAdapter());
    registerAdapter(TimeRangeHiveModelAdapter());
    registerAdapter(UserHiveModelAdapter());
    registerAdapter(WeekDayAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryHiveModelAdapter());
    registerAdapter(CustomMeasurementUnitHiveModelAdapter());
    registerAdapter(DateRangeHiveModelAdapter());
    registerAdapter(DayTypeAdapter());
    registerAdapter(GoalConstraintAdapter());
    registerAdapter(GoalHiveModelAdapter());
    registerAdapter(IntervalUnitAdapter());
    registerAdapter(MeasurementCategoryAdapter());
    registerAdapter(MeasurementUnitAdapter());
    registerAdapter(OSAdapter());
    registerAdapter(OSAdapter());
    registerAdapter(OccurrenceStatusAdapter());
    registerAdapter(PriorityAdapter());
    registerAdapter(ReferenceTypeAdapter());
    registerAdapter(RegistrationStatusAdapter());
    registerAdapter(RepetitionTypeAdapter());
    registerAdapter(ScheduleConstraintsHiveModelAdapter());
    registerAdapter(ScheduleTypeAdapter());
    registerAdapter(ScheduledDayTimeHiveModelAdapter());
    registerAdapter(ScheduledIntervalHiveModelAdapter());
    registerAdapter(ScheduledOccurrenceHiveModelAdapter());
    registerAdapter(ScheduledTimeModeAdapter());
    registerAdapter(SubTaskHiveModelAdapter());
    registerAdapter(SyncActionAdapter());
    registerAdapter(TagHiveModelAdapter());
    registerAdapter(TaskHiveModelAdapter());
    registerAdapter(TaskStatusAdapter());
    registerAdapter(TimeRangeHiveModelAdapter());
    registerAdapter(UserHiveModelAdapter());
    registerAdapter(WeekDayAdapter());
  }
}
